from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import PostViewSet

# Create a router for automatic URL routing
router = DefaultRouter()
router.register(r'posts', PostViewSet)

urlpatterns = [
    path('api/', include(router.urls)),  # Include the routes generated by the router
]
